<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Kmaraszkiewicz86.SimpleCqrs" Version="0.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\ApplicationLayer\ApplicationLayer.csproj" />
    <ProjectReference Include="..\Infrastructure.Database\Infrastructure.Database.csproj" />
    <ProjectReference Include="..\Infrastructure.Http\Infrastructure.Http.csproj" />
  </ItemGroup>

</Project>
